# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0002_author_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='blogs',
            new_name='book_author',
        ),
    ]
