# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0003_auto_20170919_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book_author',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books_authors.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
